version: "3"

services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./prisma/.env

    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
